# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - crane_controller

  crane_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - slider_fb_link_middle_link_a_joint
      - virtual_link_slider_fb_link_joint
      - sslider_ud_link_virtual_link_joint